default_platform(:ios)

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    
    # Sync certificates
    match(type: "appstore", readonly: true)
    
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ios/coachmate.xcodeproj"
    )
    
    # Ensure that your app is ready for submission
    ensure_build_directory

    # Build your iOS app
    build_ios_app(
      workspace: "ios/coachmate.xcworkspace",
      scheme: "coachmate",
      export_method: "app-store",
      output_directory: "ios/build",
      output_name: "coachmate.ipa"
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

platform :android do
  desc "Push a new beta build to Play Store Internal Testing"
  lane :beta do
    setup_ci if ENV['CI']

    # Increment version code
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )

    # Ensure that your app is ready for submission
    gradle(
      task: 'clean bundle',
      build_type: 'Release',
      project_dir: 'android/'
    )

    # Upload to Play Store Internal Testing
    upload_to_play_store(
      track: 'internal',
      aab: "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
    )
  end
end
