default_platform(:ios)

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    
    # Sync certificates
    match(type: "appstore", readonly: true)

     # Add debug statements
     puts "Current directory: #{Dir.pwd}"
     puts "File exists: #{File.exist?('./AuthKey_9KF34Z7C3A.p8')}"
    
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ios/coachmate.xcodeproj"
    )
    
    # Create build directory
    sh "mkdir -p ios/build"
    
    # Build your iOS app
    build_ios_app(
      workspace: "ios/coachmate.xcworkspace",
      scheme: "coachmate",
      export_method: "app-store",
      output_directory: "ios/build",
      output_name: "coachmate.ipa"
    )

    api_key = app_store_connect_api_key(
      key_id: "9KF34Z7C3A",
      issuer_id: "c182c483-9d61-427c-b16a-28deba60b60f",
      key_filepath: File.expand_path("./AuthKey_9KF34Z7C3A.p8"),
      duration: 1200
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

  end
end

platform :android do
  desc "Push a new beta build to Play Store Internal Testing"
  lane :beta do
    setup_ci if ENV['CI']

    # Clean the project first
    gradle(
      task: 'clean',
      project_dir: 'android/'
    )

    # Increment version code
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )

    # Build the release bundle with detailed logging
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android/',
      properties: {
        "org.gradle.jvmargs" => "-Xmx4096m"
      },
      print_command: true,
      flags: "--stacktrace --info"
    )

    # Upload to Play Store Internal Testing
    upload_to_play_store(
      track: 'internal',
      aab: "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
    )
  end
end
